name: CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: pablomk7/libctrpf:0.8.0
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: make
    - name: Publish
      uses: actions/upload-artifact@v4
      with:
        name: 3gx
        path: 3gx
