name: CI

on:
  workflow_dispatch:
  
jobs:
  build:
    name: Build boot.3dsx
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Build
      run: make -j$(nproc --all)
    - name: Publish boot.3dsx (only on manual run or release)
      uses: actions/upload-artifact@v4
      with:
        name: 3ds
        path: ./
